---
title: "tsl 3/26"
output: html_document
date: "2024-03-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(ggplot2)
```

#import data 
```{r, echo=FALSE}
tuition <- read.csv("~/Desktop/TSL/Training/tuition_5c.csv")
#tuition
```

```{r}
#colnames(tuition)
#tail(tuition)
#tuition$year <- as.Date(as.character(tuition$year), format = "%Y")
#tuition
```
## Cost of Attendance at 5Cs
```{r}

school_colors <- c("Claremont McKenna College" = "#981a31", "Pitzer College" = "#F7941D", "Harvey Mudd College" = "#FDB913", "Pomona College" = "#0057b8", "Scripps College" = "#34715b")

tuition |> 
  ggplot(aes(x= year, y=full))+
  geom_line(aes(color=school), lwd = 0.75)+
  scale_x_continuous(breaks = seq(min(tuition$year), max(tuition$year), 1))+
  ylim(59000, NA)+
  scale_color_manual(values=school_colors, name = "School")+
  theme_minimal() +
  theme(text = element_text(family = "palatino")) +
  labs(title="Cost of Attendance at The Claremont Colleges", y="Tuition (USD)", x="Year")
  #geom_point(aes(color=school))


```


## Percent Changes Over Time
```{r}

library(dplyr)
library(stringr)
tuition_per_change <- tuition %>%
  group_by(school) %>%
  mutate(full_per_change = (full / lag(full))-1)

# View the modified data frame
print(tuition_per_change)
```

```{r}
tuition_per_change %>%
  ggplot(aes(x = year, y = full_per_change)) +
  geom_line(aes(color = school), lwd = 0.75) +
  scale_x_continuous(breaks = seq(min(tuition$year), max(tuition$year), 1)) +
  scale_color_manual(values = school_colors, name = "School") +
  theme_minimal() +
  theme(text = element_text(family = "palatino")) +
  labs(title = "Percent Change of Cost of Attendance at The Claremont Colleges", 
       y = "Percent Change", 
       x = "Year")

```

## Tuition Change for Pomona 
```{r}
Pom_per_change <- tuition_per_change |> 
  filter(school == "Pomona College")


Pom_per_change$year <- as.factor(Pom_per_change$year)
Pom_per_change <- Pom_per_change |> 
  mutate(`room and board` = Pom_per_change$full - Pom_per_change$tuition)
Pom_per_change <- Pom_per_change |> 
  select(-c(full))

Pom_per_change <- Pom_per_change |> 
  pivot_longer(cols= c("tuition", "room and board"), names_to = "fee type", values_to = "fee")

Pom_per_change$`fee type` <- factor(Pom_per_change$`fee type`, levels = c("tuition", "room and board"))


chart <- Pom_per_change |> 
  ggplot(aes(x= year, y=fee, fill= `fee type`))+
  geom_bar(position = "stack", stat = 'identity')

chart <- chart +
  labs(title = "Cost of Attendance at Pomona College")+
  xlab("Year")+
  ylab("Amount in Dollars")+
  scale_fill_manual(name = "Fee Type", labels = c("Tuition", "Room and Board"), 
                    values=c('darkblue', 'lightgray'))
```

```{r}
#Pom_per_change
```

```{r}
tuition_data <- subset(Pom_per_change, `fee type` == "tuition")
tuition_data
```
```{r}
tuition_data <- tuition_data |> 
  mutate(text_lab = paste0(round(tuition_data$full_per_change * 100, digits = 1)))

#tuition_data
```
## Percent Change -- Pomona College
```{r}
chart + 
  geom_line()+
  geom_text(data = subset(tuition_data, !is.na(tuition_data$full_per_change)), 
            aes(label = paste0(text_lab, "%"), 
                color = 'green4'), nudge_y = c(+19800, +20250, +21005, +21650, +22216, +22718, +23320, +24024, +24958))+
  ylim(NA, 87500)+
  theme_minimal() +
  theme(text = element_text(family = "palatino")) +
  labs(title = "Percent Change of Cost of Attendance Pomona College")+ 
  scale_color_identity()
  
```
