---
title: "tt 6:27:24"
output: html_document
date: "2024-06-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
ewf_appearances <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-16/ewf_appearances.csv')
ewf_matches <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-16/ewf_matches.csv')
ewf_standings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-07-16/ewf_standings.csv')
```


```{r}
View(ewf_appearances)
View(ewf_matches)
View(ewf_standings)
```

```{r}
library(tidyverse)
```


```{r}
tier1_standings <- filter(ewf_standings, tier == 1)
season_point_totals <- tier1_standings |> 
  group_by(season) |> 
  summarise(total_points = sum(points))

tier1_standings <- inner_join(tier1_standings, season_point_totals, by = "season") |> 
  mutate(season_point_totals)
```

```{r}
View(tier1_standings)
```

