---
title: "Leap Day Births"
output: html_document
date: "2024-02-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(babynames)
```

```{r}
events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-27/events.csv')
births <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-27/births.csv')
deaths <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-27/deaths.csv')
```

```{r}
births <- births |>
  separate(person, c("Fname", "Lname"))
```



```{r}
leap_names <- births |> 
  group_by(Fname) |> 
  summarize(count = n()) |> 
  filter(count >= 2)

leap_names


leap_births <- babynames |> 
  filter(year > 1920) |> 
  filter(name %in% leap_names$Fname) |> 
  group_by(name, year) |> 
  mutate(diff = n - log(n))

leap_births
```

```{r}
leap_births |> 
  ggplot(aes(x = year, y = n)) +
  geom_line(aes(color = name, lty = sex)) +
  geom_point(data = filter(births, Fname %in% leap_names$Fname),
             aes(color = Fname, x = year_birth), y = 75000, size = 5) +
  xlim(1950, 2010) +
  labs(x = "Year", y = "Count", title = "Name Popularity", color = "Name", lty = "Sex") +
  theme_minimal() +
  theme(
    text = element_text(family = "Times New Roman"),
    plot.title = element_text(face = "bold")
  )
```

