---
title: "Math 58B HW6"
author: "Jazelle Saligumba"
date: " Due: 3/27/2024 "
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Read directly from GitHub

eclipse_annular_2023 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_annular_2023.csv')
eclipse_total_2024 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_total_2024.csv')
eclipse_partial_2023 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_partial_2023.csv')
eclipse_partial_2024 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_partial_2024.csv')

```

```{r}
#View(eclipse_annular_2023)
#View(eclipse_total_2024)
#View(eclipse_partial_2023)
#View(eclipse_partial_2024)
library(tidyverse)
```

```{r}
tot_24 <- eclipse_total_2024 |> 
  mutate(time = eclipse_6 - eclipse_1,
         eclipse = "total") |> 
  select(state, name, lat, lon, time, eclipse)

part_24 <- eclipse_partial_2024 |> 
  mutate(time = eclipse_5 - eclipse_1,
         eclipse = "partial") |> 
  select(state, name, lat, lon, time, eclipse)

eclipse_24 <- rbind(tot_24, part_24) |> 
  mutate(time = as.numeric(time))
  
```

```{r}
library(ggnewscale)
 # | fig-cap: In blue, the path of the 2024 annular eclipse. The times represent the difference (in seconds) between when the moon first contacts the sun and when the moon last contacts the sun. 

states <- map_data("state")

ggplot(states) +
  geom_polygon(fill = "white", color = "black",
               aes(long, lat, group=group)) +
  geom_point(data = filter(eclipse_24, lat < 51 & lat > 24 & lon < 0 & eclipse == "total"),
             aes(x= lon, y = lat, color = time), size = 0.0001) +
  scale_colour_gradientn(colors = c("turquoise", "blue")) +
  labs(color = "time of overlaps (sec)\ntotal eclipse") +
  new_scale_color() +
  geom_point(data = filter(eclipse_24, lat < 51 & lat > 24 & lon < 0 & eclipse == "partial"), 
             aes(x = lon, y = lat, color = time), size = 0.0001) +
  scale_colour_gradientn(colors = c("red", "hotpink")) +
  ggtitle("2024 solar eclipse") +
  labs(color = "time of overlaps (sec)\npartial eclipse")
  
```
```{r}
tot_23 <- eclipse_annular_2023 |> 
  mutate(time = eclipse_6 - eclipse_1,
         eclipse = "total") |> 
  select(state, name, lat, lon, time, eclipse)

part_23 <- eclipse_partial_2023 |> 
  mutate(time = eclipse_5 - eclipse_1,
         eclipse = "partial") |> 
  select(state, name, lat, lon, time, eclipse)

eclipse_23 <- rbind(tot_23, part_23) |>  # bind rows
  mutate(time = as.numeric(time))

```

```{r}
 # | fig-cap: In blue, the path of the 2023 annular eclipse. The times represent the difference (in seconds) between when the moon first contacts the sun and when the moon last contacts the sun. 
states <- map_data("state")

ggplot(states) +
  geom_polygon(fill = "white", color = "black",
               aes(long, lat, group=group)) +
  geom_point(data = filter(eclipse_23, lat < 51 & lat > 24 & lon < 0 & eclipse == "total"),
             aes(x= lon, y = lat, color = time), size = 0.0001) +
  labs(x = " ", y = " ") +
  scale_colour_gradientn(colors = c("turquoise", "blue")) +
  labs(color = "time of overlaps (sec)\ntotal eclipse") +
  new_scale_color() +
  geom_point(data = filter(eclipse_23, lat < 51 & lat > 24 & lon < 0 & eclipse == "partial"), 
             aes(x = lon, y = lat, color = time), size = 0.0001) +
  scale_colour_gradientn(colors = c("red", "pink")) +
  ggtitle("2023 solar eclipse") +
  labs(color = "time of overlaps (sec)\npartial eclipse")
```

```{r}
library(praise)
praise()
```

